steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/openfisca-japan-dev:$COMMIT_SHA",
        "-f",
        "Dockerfile_cloud",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/openfisca-japan-dev:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "openfisca-japan-dev"
      - "--image"
      - "gcr.io/$PROJECT_ID/openfisca-japan-dev:$COMMIT_SHA"
      - "--region"
      - "us-central1"
images:
  - "gcr.io/$PROJECT_ID/openfisca-japan-dev:$COMMIT_SHA"
