# Always launch panes with bash, regardless of the exec'd process's $SHELL or the
# user's /etc/passwd shell field (which defaults to /bin/sh via `useradd` otherwise).
set -g default-shell /bin/bash

# Enable mouse interactions, including scrolling through pane history with the wheel.
set -g mouse on
set -g set-clipboard on

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
